### ISSUE TITLE
Discux! 3.4 https 无法上传

### ISSUE THREAD

**Issue by luodaoyi** [sxyazi/qiniu#6]
提示 http://upload.qiniu.com 不是Https  无法上传

php版本 7.2
Mixed Content: The page at 'xxxxxxxx' was loaded over HTTPS, but requested an insecure form action 'http://upload.qiniu.com/'. This request has been blocked; the content must be served over HTTPS.

**Comment by sxyazi** [comment]
https://github.com/sxyazi/qiniu/blob/58607bbc476bc498ce98e2caed8a7127fda6222f/template/cate_upload.htm#L10
https://github.com/sxyazi/qiniu/blob/58607bbc476bc498ce98e2caed8a7127fda6222f/template/maile_upload.js#L21

把这两个文件中的 `http://upload.qiniu.com/` 改为 `https://upload.qiniu.com/` 即可。
